### ISSUE TITLE
support for static site generation (server-side rendering)

### ISSUE THREAD

**Issue by joelhooks** [hc-oss/use-indexeddb#408]
Currently when you are in a server environment the provider replaces all of the children with `null` or the `loading` fallback. 

It would be fantastic if the Provider and the hooks would `noop` when the indexeddb wasn't available in the environment. Maybe as an option. 

I'm going to look at the code more in depth to see if I can supply a PR, but wanted to understand "why" it behaves as it does more.

**Comment by harshzalavadiya** [comment]
@joelhooks Yeah, it might be nice to have some workaround

as of now constrains are as below
- IndexedDB can't be executed on Server Side and since DB is in browser.
- and if we make query before indexedDB context gets connection which may take time and sometimes even after `useEffect` so it won't break existing rendering cycle or throw error

**Comment by harshzalavadiya** [comment]
@joelhooks new `v2.0.0` should make very easy to access
